<?php
$apps=array(
    array("nombre"=>"Turnos","nivel"=>"Todos","html"=>"turnos.html","menu"=>"Si"),
    array("nombre"=>"Agendas","nivel"=>"Prof","html"=>"agendas.html","menu"=>"Si"),
    array("nombre"=>"Horarios","nivel"=>"Admin","html"=>"horarios.html","menu"=>"Si"),
    array("nombre"=>"Usuarios","nivel"=>"Admin","html"=>"usuarios.html","menu"=>"Si"),
    array("nombre"=>"Pedidos","nivel"=>"Admin","html"=>"pedidos.html","menu"=>"Si"),
    array("nombre"=>"Historicos","nivel"=>"Admin","html"=>"historicos.html","menu"=>"Si"),
    array("nombre"=>"Login","nivel"=>"Todos","html"=>"login.html","menu"=>"No"),
    array("nombre"=>"Confirmado","nivel"=>"Todos","html"=>"confirmado.html","menu"=>"No"),
    array("nombre"=>"PagarMP","nivel"=>"Todos","html"=>"pagarmp.html","menu"=>"No"),
    array("nombre"=>"PagarPaypal","nivel"=>"Todos","html"=>"pagarpaypal.html","menu"=>"No"),
    array("nombre"=>"Recepcion","nivel"=>"Todos","html"=>"recepcionpago.html","menu"=>"No")
);
?>
